Fix wiki name directory issue while performing create action
CanastaWiki/Canasta-Go pull request #103
Opened 2024-03-13 18:56 UTC by TechieNK

2024-04-26 03:40 UTC, jeffw16 commented on cmd/create/create.go
> +			name = strings.Replace(name, " ", "_", -1)
What does the name refer to? Directory name or the wiki name? It does not make sense to have `$wgSitename` be something like "My_New_Canasta_Wiki".

2024-04-26 15:00 UTC, TechieNK commented on cmd/create/create.go
> +			name = strings.Replace(name, " ", "_", -1)
It is the Wiki name.

2024-04-26 16:11 UTC, jeffw16 commented on cmd/create/create.go
> +			name = strings.Replace(name, " ", "_", -1)
In that case it would be silly to replace the spaces with underscores.

2024-04-26 16:12 UTC, jeffw16 requested changes
I have concerns about replacing the spaces with underscores for $wgSitename

2024-05-16 16:39 UTC, yaronkoren approved these changes

2024-05-16 16:40 UTC, yaronkoren commented
@jeffw16 - please re-review! The patch is totally different now.

2024-08-13 16:32 UTC, merged