Move password length validation to pre-create stage
CanastaWiki/Canasta-Go pull request #104
Opened 2024-04-16 16:59 UTC by TechieNK

2024-05-02 19:26 UTC, jeffw16 requested changes

2024-05-02 19:26 UTC, jeffw16 commented on internal/prompt/prompt.go
> +	if len(password) < 10 {
Why did we move this away from its own function? This makes it less unit testable.

2024-06-21 16:45 UTC, jeffw16 commented
Can we write some unit tests to ensure this function works correctly?

2024-06-21 17:15 UTC, naresh-kumar-babu commented
> Can we write some unit tests to ensure this function works correctly?

Added unit test.

2024-06-21 17:16 UTC, jeffw16 approved these changes

2024-06-21 17:17 UTC, merged