Delete installation on failure
CanastaWiki/Canasta-Go pull request #19
Opened 2022-09-05 18:59 UTC by amalpaul54111

Fixes #14
So when a create/import command fails, `canasta` CLI asks the user whether to keep the config files or not.

2022-09-05 22:34 UTC, hexmode commented
Tested.

Looks pretty good to me.  I would prefer a CLI option to keep and then change the default to delete, but if @jeffw16 or @yaronkoren like this implementation, it works.

2022-09-06 00:46 UTC, yaronkoren commented
@hexmode - great!

I think this is good - even if the plan is to add a "keep on failure" option, this is a step in the right direction anyway. (A big step.)

2022-09-06 06:35 UTC, jeffw16 commented
I agree with @hexmode: it should be delete by default.

2022-09-06 06:35 UTC, jeffw16 requested changes

2022-09-06 06:35 UTC, jeffw16 commented on cmd/create/create.go
> +				if input == "y" {
Please change to delete by default, keep only by explicit request

2022-09-06 06:36 UTC, jeffw16 commented on cmd/create/create.go
> +				if input == "y" {
Also I'm pretty sure we can do better than simply checking for a lowercase `y` or `n`. There's more possible cases, such as `yes` or `no`.

2022-09-06 06:58 UTC, amalpaul54111 commented on cmd/create/create.go
> +				if input == "y" {
> Also I'm pretty sure we can do better than simply checking for a lowercase `y` or `n`. There's more possible cases, such as `yes` or `no` or `Y` or `N`.

Yeah, sure. 

> Please change to delete by default, keep only by explicit request

Okay, also should there be a CLI option to keep the files, so it does not prompt?

2022-09-06 15:46 UTC, yaronkoren commented on cmd/create/create.go
> +				if input == "y" {
I would say, in the interests of time (and keeping this patch manageable), don't worry about adding an option to keep the files - it would be nice to have, but it can always be added later.

2022-09-07 06:48 UTC, jeffw16 commented on cmd/create/create.go
> +				if input == "y" {
I agree with @yaronkoren

2022-09-09 16:48 UTC, jeffw16 approved these changes

2022-09-09 17:01 UTC, merged