Add documentation for managing existing canasta instance
CanastaWiki/Canasta-Go pull request #20
Opened 2022-09-05 19:13 UTC by amalpaul54111

Fixes #18

2022-09-06 01:58 UTC, yaronkoren commented
This looks good to me, aside from a few small typos... anyone else?

2022-09-06 06:33 UTC, jeffw16 requested changes
Please fix linguistic syntactical issues

2022-09-06 06:33 UTC, jeffw16 commented on README.md
> +"Id"   - Represent the Canasta Id used by the cli to differentiate between installations.
ID* not "Id" (that's a Freudian concept)

2022-09-06 06:33 UTC, jeffw16 commented on README.md
> +"Path" - The location where the configuration files(i.e. 'docker-compose.yaml' and other such files) are saved.
Please add a space between files and (i.e.

2022-09-06 06:33 UTC, jeffw16 commented
Typos need to be resolved please.

2022-09-06 12:41 UTC, yaronkoren commented
If we're already covering typos, I see a few more: "add a object" should be "add an object", and "Represent the Canasta ID used by the cli" should by "Represents the Canasta ID used by the CLI".

2022-09-06 16:25 UTC, yaronkoren approved these changes

2022-09-09 16:29 UTC, amalpaul54111 commented
Since, we are moving the CLI documentation to [Canasta-Documentation](https://github.com/CanastaWiki/Canasta-Documentation), this PR could be closed right? 
All the changes requested here have been implemented at https://github.com/CanastaWiki/Canasta-Documentation/pull/2

2022-09-09 16:58 UTC, yaronkoren commented
Sure, let's just close it...

2022-09-09 16:58 UTC, closed without merging