Add backup command
CanastaWiki/Canasta-Go pull request #3
Opened 2022-07-15 16:53 UTC by amalpaul54111

Added minimum backup commands based on @lexsulzer 's https://github.com/dataspects/mediawiki-cli/tree/canasta/manage-snapshots-canasta

1. init
2. view
3. take-snapshot
4. restore

2022-07-29 21:16 UTC, jeffw16 requested changes

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/check.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "check")
fix spacing between `+`

also, this seems repetitive to me. Every file will do execute.Run docker run restic etc., the only thing that is different seems to be the last parameter

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/diff.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "diff",
fix spacing between `+`

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/forgetSnapshots.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "forget"
fix

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/init.go
> +	execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "init")
fix

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/listFiles.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "ls", ta
fix

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/unlock.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "unlock"
see above

2022-07-29 21:16 UTC, jeffw16 commented on cmd/restic/viewSnapshots.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "snapsho
see above

2022-07-31 10:15 UTC, amalpaul54111 commented on cmd/restic/check.go
> +	output := execute.Run(instance.Path, "sudo", "docker", "run", "--rm", "-i", "--env-file", envPath, "restic/restic", "-r", "s3:"+EnvVariables["AWS_S3_API"]+"/"+EnvVariables["AWS_S3_BUCKET"], "check")
About the spacing between ` + `. 
Go provides a tool named `gofmt` and VS Code uses the same to format the code. And it prefers to remove the space between the `+` always.

Yeah, I will also fix the repetitive usage of the sudo docker run.

2022-07-31 13:51 UTC, yaronkoren commented
Yes, indeed - it looks like people have complained about gofmt's strange spacing for a long time, but it's what the developers want:

https://github.com/golang/go/issues/12720

Given that, I think we should stick with gofmt's output.

2022-08-03 16:48 UTC, jeffw16 approved these changes

2022-08-03 17:18 UTC, merged