feat: Add option to choose version to install
CanastaWiki/Canasta-Go pull request #35
Opened 2022-10-30 11:22 UTC by ha36d

fixes CanastaWiki/Canasta-CLI#34

Signed-off-by: Hamed Faramarzi <hamed.faramarzi@gmail.com>

2022-10-30 12:39 UTC, jeffw16 requested changes
Thanks for the contribution!

2022-10-30 12:39 UTC, jeffw16 commented on install.sh
> +#!/usr/bin/env bash
Any specific reason to change the interpreter path?

2022-10-30 12:39 UTC, jeffw16 commented on install.sh
> +  if [ $? -ne 0 ]; then
Can we avoid duplicating this if statement

2022-10-30 12:39 UTC, jeffw16 commented on install.sh
> +    read -rp "Version (i.e. 1.2.0): " -e VERSION
Change `i.e.` to `e.g.`

2022-10-30 12:39 UTC, jeffw16 commented on install.sh
> +    echo "Canasta CLI with the version you have chosen, does not exist."
Please change to `The version you have specified is not a valid version of the Canasta CLI.`

2022-10-30 13:16 UTC, ha36d commented on install.sh
> +#!/usr/bin/env bash
yes, because the `-i` is not supported in Mac Bash. It should be updated, and everyone update it via brew. It will not impact linux ones.

2022-10-30 13:19 UTC, ha36d commented on install.sh
> +    read -rp "Version (i.e. 1.2.0): " -e VERSION
sure

2022-10-30 13:22 UTC, ha36d commented on install.sh
> +    echo "Canasta CLI with the version you have chosen, does not exist."
Done.

2022-10-30 13:22 UTC, ha36d commented on install.sh
> +  if [ $? -ne 0 ]; then
Done

2022-10-30 13:30 UTC, jeffw16 requested changes

2022-10-30 13:30 UTC, jeffw16 commented on install.sh
> +echo "Which version do you want to install?"
It's important to keep a non-interactive version of this script. The behavior should be as follows:

- By default, if this script is called normally, the latest version is installed.
- If a flag `--version` or `-v` is passed in with the desired version, install the specified version.
- If a flag `--interactive` or `-i` is passed in, prompt what exists right now.

2022-10-30 14:19 UTC, ha36d commented on install.sh
> +echo "Which version do you want to install?"
Done.

2022-10-30 15:45 UTC, jeffw16 approved these changes

2022-12-20 15:31 UTC, yaronkoren commented
Note: this is a fix for issue #34.

2022-12-20 15:40 UTC, yaronkoren commented
@ha36d - I'm sorry for the very long delay in reviewing this patch; I wasn't paying enough attention to CLI pull requests before. This overall looks good - but I think the "interactive mode" is unnecessarily complex, and doesn't make the "version" feature any easier to use, I don't think. I think just the "-v" flag should be enough; people will understand what it means. Could you simplify this patch? I hope you are still willing to do some work on this...

2022-12-20 15:55 UTC, yaronkoren commented
Actually, another comment: calling the flag "-v" might not be all that clear, since people might think it refers to the version of the Canasta CLI. (Or even the version of the installer, for that matter...) Could you change it to something like "-canasta_version"?

2023-05-05 16:31 UTC, yaronkoren commented
Closing/rejecting this PR - it still has some issues, and in the meantime it has been superseded by #77.

2023-05-05 16:31 UTC, closed without merging