Add Upgrade command
CanastaWiki/Canasta-Go pull request #36
Opened 2022-11-02 18:07 UTC by amalpaul54111

Add the “canasta upgrade” command, which will update the canasta installation to the latest version.

2023-02-13 03:29 UTC, bawolff requested changes
So I assume that upgrading canasta versions can sometimes upgrade MediaWiki?

If so, I would recommend running the update.php maintenance script as part of this. I would also recommend `touch` -ing LocalSettings.php, as that triggers a cache flush in MediaWiki (for some types of caches).

Other than that, this looks good.

2023-02-16 19:39 UTC, amalpaul54111 commented
Yeah sure, that can be done.

2023-02-17 18:03 UTC, amalpaul54111 commented
Should we explicitly run the “update.php” maintenance script since we are already doing a **restart** and as the Canasta container image does run the “update.php” scrip as part of the **run_apache.sh** script on container startup. 

Also would a restart of the container flush cache or is it necessary to do  “touch LocalSettings.php”?

2023-02-20 05:34 UTC, bawolff commented
> Should we explicitly run the “update.php” maintenance script since we are already doing a restart and as the Canasta container image does run the “update.php” scrip as part of the run_apache.sh script on container startup.

Oh, i didn't realize that. Given that, not running update.php here makes sense.

> Also would a restart of the container flush cache or is it necessary to do “touch LocalSettings.php”?

Touching LocalSettings.php will trigger browser cache to flush (i.e. prevent sending 304 Not Modified for stuff pre-touch), flush parser cache, and flush file cache. Restarting the container will probably flush parser cache (Assuming we are not using CACHE_DB) but I don't believe it will flush browser cache (And i don't think file cache is relevant to canasta). So its probably still a good idea, but  also not critical.

2023-02-20 06:30 UTC, amalpaul54111 commented
Okay, could add 'touch LocalSettings.php', just wanted to clarify.

2023-02-24 21:18 UTC, bawolff requested changes

2023-02-24 21:18 UTC, bawolff commented on cmd/upgrade/upgrade.go
> +	execute.Run(instance.Path, "touch", "config/LocalSettings.php")
This won't work because that's not the real LocalSettings.php file, so MediaWiki won't detect the change. Would probably have to touch `/var/www/mediawiki/w/LocalSettings.php` inside the web container for this to work.

Although this does raise an interesting point, that when ordinary users edit LocalSettings.php in Castana, they are going to edit config/LocalSettings.php, which won't have the cache clearing affect that would happen in a normal mediawiki install.

2024-02-13 22:04 UTC, yaronkoren commented
This code was more-or-less merged in, with some modifications, in #102. @amalpaul54111 - thank you for your work on this!

2024-02-13 22:04 UTC, closed without merging