Fix config dir
CanastaWiki/Canasta-Go pull request #48
Opened 2022-12-09 07:31 UTC by amalpaul54111

Fix #42
1. Remove error saying missing "/root/.config" directory which is not used.
2. Create ".config" in users home directory if it does not exist.

2022-12-09 15:57 UTC, yaronkoren commented
@hexmode - what do you think, does this look like correct logic?

2022-12-09 18:28 UTC, hexmode requested changes

2022-12-09 18:28 UTC, hexmode commented on internal/config/config.go
> +	} else if currentUser.Username != "root" {
this should just be else

2022-12-09 18:28 UTC, hexmode commented on internal/config/config.go
> +			var configDir string = ".config"
This should use the current value of dir.

2022-12-09 18:28 UTC, hexmode commented on internal/config/config.go
> +			err = os.Mkdir(configDir, os.ModePerm)
This should use [os.MkdirAll](https://pkg.go.dev/os#MkdirAll).

2022-12-09 18:28 UTC, hexmode commented on internal/config/config.go
> +			}
exists should be set to true here

2022-12-09 19:24 UTC, amalpaul54111 commented on internal/config/config.go
> +	} else if currentUser.Username != "root" {
Oh, sorry, that's right.

2022-12-11 10:22 UTC, amalpaul54111 commented
@hexmode I have made the requested changes. 
Since the `config.init()` is being executed even before setting the verbose, used the `log.Print()` inside both the `config.GetConfigDir()` and `config.init()`
Also removed the repeated section which verified the configuration directory existed.

2023-02-12 00:03 UTC, bawolff requested changes
I'm not sure I understand the intention of this code.

If the goal is that every user has a separate config file, then i think it makes more sense for the root user to use /root/.config/canasta . Normally I would expect a file in /etc to be shared by all users. That said, if this was to be shared by all users, I would probably expect it in /var/local since this is state related data and not configuration related data.

2023-02-12 00:03 UTC, bawolff commented on internal/config/config.go
> +		err = os.MkdirAll(dir, os.ModePerm)
os.ModePerm (= o777) seems like the incorrect permissions here.

Assuming this config file is meant to be per-user with no secret data, I would expect permissions to be o755

2023-02-13 16:00 UTC, yaronkoren commented
@bawolff - by "this code", do you mean this patch, or the underlying .config file feature? If it's this latter, that discussion probably makes more sense in a separate issue/PR - though we should definitely have that discussion.

2023-02-14 09:23 UTC, bawolff commented
> @bawolff - by "this code", do you mean this patch, or the underlying .config file feature? If it's this latter, that discussion probably makes more sense in a separate issue/PR - though we should definitely have that discussion.

I meant the underlying, put config in /etc if you are root feature (Or perhaps the idea of having different config files for different users in general).  And yes, that sounds fair.

My only other objection was that the directory should probably be 0755 or 0700 depending on your level of paranoia not 0777,  however that also seems to be copied over from the previous version of the file, and is probably a separate issue from the thing this patch is trying to fix. So with that in mind, this patch looks good, and I'll file a separate issue to further discuss the config file thing.

2023-02-14 09:23 UTC, bawolff approved these changes

2023-02-14 21:52 UTC, yaronkoren approved these changes

2023-02-14 22:03 UTC, tosfos approved these changes

2023-02-14 22:05 UTC, tosfos commented on internal/config/config.go
> +		err = os.MkdirAll(dir, os.ModePerm)
To be addressed in #64

2023-02-14 22:06 UTC, merged