Test for git
CanastaWiki/Canasta-Go pull request #52
Opened 2022-12-15 02:19 UTC by gitmapd

Added test for git and replaced "which", there are distributions that "which" doesn't exist, it's not portable.

2022-12-15 02:28 UTC, gitmapd commented
I forgot to change the shebang to #!/usr/bin/env bash .

2022-12-17 20:52 UTC, jeffw16 requested changes, later dismissed

2022-12-17 20:52 UTC, jeffw16 commented on install.sh
>  loc=$(which docker)
`which` and the lines below it that use the `$loc` variable don't seem to be removed from here.

2022-12-17 22:24 UTC, gitmapd commented
Hi, I apologize but i don't get your sentence. Thanks.

On Sat, 17 Dec 2022 at 20:52, Jeffrey Wang ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In install.sh
> <https://github.com/CanastaWiki/Canasta-CLI/pull/52#discussion_r1051481958>
> :
>
> > @@ -18,6 +18,18 @@ echo "Installing Canasta CLI"
>  chmod u=rwx,g=xr,o=x canasta
>  sudo mv canasta /usr/local/bin/canasta
>
> +# Testing git if installed else tell to install it
> +git --version 2>&1 >/dev/null
> +
> +GIT_IS_AVAILABLE=$?
> +
> +if [ $GIT_IS_AVAILABLE -ne 0 ];
> +then echo "Git was not found, please install before continuing.";
> +     exit;
> +else
> +     echo "Git was found on the system"
> +fi
> +
>  loc=$(which docker)
>
> which and the lines below it that use the $loc variable don't seem to be
> removed from here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CanastaWiki/Canasta-CLI/pull/52#pullrequestreview-1221893903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL55ONSNGQHKWJEMATRDXL3WNYRZBANCNFSM6AAAAAAS7GMPU4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-17 22:25 UTC, jeffw16 commented on install.sh
>  loc=$(which docker)
You said you replaced `which` because it's not portable, but your new code still contains `which`.

2022-12-17 22:28 UTC, gitmapd commented
I know i i think you got to see the comment before I removed it, but Yaron
told me to make a new patch for it. There is another patch to change the
shebang, do you want me to make a patch with which + the shebang changed?

On Sat, 17 Dec 2022 at 22:26, Jeffrey Wang ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In install.sh
> <https://github.com/CanastaWiki/Canasta-CLI/pull/52#discussion_r1051491726>
> :
>
> > @@ -18,6 +18,18 @@ echo "Installing Canasta CLI"
>  chmod u=rwx,g=xr,o=x canasta
>  sudo mv canasta /usr/local/bin/canasta
>
> +# Testing git if installed else tell to install it
> +git --version 2>&1 >/dev/null
> +
> +GIT_IS_AVAILABLE=$?
> +
> +if [ $GIT_IS_AVAILABLE -ne 0 ];
> +then echo "Git was not found, please install before continuing.";
> +     exit;
> +else
> +     echo "Git was found on the system"
> +fi
> +
>  loc=$(which docker)
>
> You said you replaced which because it's not portable, but your new code
> still contains which.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CanastaWiki/Canasta-CLI/pull/52#discussion_r1051491726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL55ONT3GAI465CY6PQFEUTWNY4XZANCNFSM6AAAAAAS7GMPU4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-20 15:44 UTC, yaronkoren commented
Note: this fixes issue #26.

2023-02-16 17:24 UTC, bawolff approved these changes
If the point is to make this posix compliant, this doesn't accomplish it (as the docker check still uses which), but as a step in the right direction seems reasonable

2023-02-17 03:20 UTC, yaronkoren approved these changes

2023-02-17 03:37 UTC, yaronkoren commented on install.sh
>  loc=$(which docker)
These comments are not relevant to the actual code additions, I think - just to the commit summary.

2023-02-17 03:38 UTC, merged