Makefile to build Canasta-CLI
CanastaWiki/Canasta-Go pull request #53
Opened 2022-12-16 15:53 UTC by gitmapd

Makefile:
- Builds the canasta-cli go project.
- Checks syntax errors.

2022-12-17 20:51 UTC, jeffw16 commented
I want to get a review done by @hexmode first if possible, since he is more experienced with Makefiles.

2022-12-18 18:49 UTC, hexmode commented
> I want to get a review done by @hexmode first if possible, since he is more experienced with Makefiles.

I'll try to look at this later this week.

2023-02-13 01:55 UTC, bawolff requested changes
You need to use tabs not spaces. This is not just a stylistic difference in makefiles.

This seems to have a lot of targets that don't do anything (benchmark, test, etc). I suppose they might in future though. I'm not sure if that is wanted.

I think this should  include the extra ldflags like build.sh does.

The makefile seems to unconditionally rebuild, even if no files have changed. I suppose that is intentional?

2023-02-13 01:55 UTC, bawolff commented on Makefile
> +build:
Should these targets be declared as .PHONY ?

2023-02-13 01:55 UTC, bawolff commented on Makefile
> +benchmark:
Kind of odd to have a benchmark target when there are no benchmarks.

2023-02-13 17:28 UTC, hexmode commented
@bawolff thanks for reviewing this. I lost track of it.

2024-02-12 18:49 UTC, closed without merging

2024-02-12 18:49 UTC, yaronkoren commented
An improved version of this patch was implemented in #100.