Add progress bar to Canasta Create
CanastaWiki/Canasta-Go pull request #54
Opened 2022-12-20 14:05 UTC by gitmapd

2022-12-20 15:43 UTC, yaronkoren commented
Note: this is a fix for issue #25.

2023-02-12 02:55 UTC, bawolff requested changes
When i try to build i get:
```
# github.com/CanastaWiki/Canasta-CLI-Go/cmd/create
cmd/create/create.go:71:9: undefined: progressbar
```

Additionally, I'm not sure this progress bar is meaningfully fine-grained enough. The first time you start Canasta, a lot of the time is going to be spent in the `docker-compose up -d` phase, since all the images have to be downloaded and built, which may be a significant amount of time. I'm not sure that having the progress bar be stuck on 45% is really all that much better than not having a progress bar.

2023-02-12 02:55 UTC, bawolff commented on cmd/create/create.go
> +	bar := progressbar.Default(100)
This seems to be missing an import

2024-02-12 14:59 UTC, closed without merging

2024-02-12 14:59 UTC, yaronkoren commented
A separate approach to this (using spinners instead of a progress bar) was just checked in, in #101.