Installer for canasta-cli
CanastaWiki/Canasta-Go pull request #56
Opened 2023-01-02 22:05 UTC by gitmapd

Finds availability for git,jq,docker,docker-compose. Allows to install different versions based on the tags.

2023-02-13 02:24 UTC, bawolff requested changes
How portable is this shell script meant to be?

If its meant to be super portable so that it can be installed everywhere, I would suggest not targeting bash but targeting /bin/sh, avoiding using jq (Commonly not installed on servers), and maybe picking one of either wget or curl to use.

[My main request change is for not including wget and curl in the list of binaries to check for. My other comments are more nice to haves]

2023-02-13 02:24 UTC, bawolff commented on install.sh
> +result=$(is_command_available git docker jq docker-compose)
You don't check for wget and curl, which are both used.

Probably makes sense to pick one of wget or curl, since they both do the same thing and  it would be good to minimize number of dependencies in the install script.

2023-02-13 02:24 UTC, bawolff commented on install.sh
> +			die "Illegal option ${1}"
Not critical, but would kind of be nice if this showed a help message listed supported arguments.

2023-02-13 02:24 UTC, bawolff commented on install.sh
> +	wget "${wargs[@]}" "$canastaURL"
Should probably include an argument specifying where to save. If a file named canasta already exists in the directory, this will save it as canasta.2 and then try to move the wrong file.

2024-02-05 16:09 UTC, yaronkoren commented
Closing this PR - this functionality, more or less, was added in with a separate patch, #77.

2024-02-05 16:09 UTC, closed without merging