Add command to manage Extensions/skins
CanastaWiki/Canasta-Go pull request #6
Opened 2022-07-25 11:30 UTC by amalpaul54111

2022-07-25 16:50 UTC, jeffw16 commented
To-do:
- Only list directories rather than files too (so we can't enable the "README" "extension" and "skin")
- Add a comment line saying "This file was generated by Canasta"; the CLI only does stuff if that exists in the file
- Add multiple extensions and skins at the same time, with names separated by commas
- Ensure idempotency so that existing files shouldn't be overridden

Wish list:
- Add adjacency list of dependencies
- Support for adding/removing user-added extensions? (Let's not worry about this for now)

2022-07-29 21:19 UTC, jeffw16 requested changes

2022-07-29 21:19 UTC, jeffw16 commented on internal/extensionsskins/extensionsskins.go
> +	output := orchestrators.Exec(instance.Path, instance.Orchestrator, "web", "cd $MW_HOME/"+constants.RelativeInstallationPath+" && find * -maxdepth 0 -type d")
please add spaces between `+` for all instances in which string concatenation occurs in this PR

2022-07-31 19:48 UTC, amalpaul54111 commented on internal/extensionsskins/extensionsskins.go
> +	output := orchestrators.Exec(instance.Path, instance.Orchestrator, "web", "cd $MW_HOME/"+constants.RelativeInstallationPath+" && find * -maxdepth 0 -type d")
As Yaron mentioned in the other pull request, it's something done by the `gofmt` the code formatting tool for golang.

2022-08-03 04:23 UTC, yaronkoren commented
This looks fine to me - the only issue I see is that "canasta-extension" and "canasta-skin" should instead be "Canasta extension" and "Canasta skin". Normally I wouldn't care about small typos like this, but it shows up a bunch of times.

2022-08-03 04:25 UTC, jeffw16 commented
Agreed with Yaron ^

2022-08-03 16:49 UTC, jeffw16 approved these changes

2022-08-03 17:24 UTC, merged