Add elasticsearch index command to Canasta-CLI
CanastaWiki/Canasta-Go pull request #60
Opened 2023-01-30 19:01 UTC by gitmapd

Approach to issue [https://github.com/CanastaWiki/Canasta-CLI/issues/41](url)

2023-01-30 19:04 UTC, yaronkoren commented
Fixes #41 .

2023-02-13 05:09 UTC, bawolff requested changes
I think this should clarify that this command is for the initial setup, and if you are upgrading your copy of cirrusSearch or if you want to force a reindex, you need to use different commands (At least as far as i can tell, based on docs https://gerrit.wikimedia.org/g/mediawiki/extensions/CirrusSearch/%2B/HEAD/UPGRADE https://gerrit.wikimedia.org/g/mediawiki/extensions/CirrusSearch/%2B/HEAD/README and https://wikitech.wikimedia.org/wiki/Search#Smaller_indices . I am not super familiar with ElasticSearch)


If CirrusSearch is not enabled, you get a really confusing error message: `Error from line 722 of /var/www/mediawiki/w/maintenance/includes/Maintenance.php: Class 'CirrusSearch\Maintenance\IndexNamespaces' not found`. I think this command should check if CirrusSearch is enabled, and give a more helpful error message if it is not.

2023-02-13 05:09 UTC, bawolff commented on cmd/elasticsearch/elasticsearch.go
> +                Short: "A brief description of your command",
These descriptions should be updated.

2023-02-13 05:09 UTC, bawolff commented on cmd/elasticsearch/index.go
> +                Short: "A brief description of your command",
ditto

2023-02-18 18:39 UTC, amalpaul54111 commented on cmd/elasticsearch/index.go
> +        orchestrators.Exec(instance.Path, instance.Orchestrator, "web", "php extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php")
The `UpdateSearchIndexConfig.php` also need `--startOver` as recommended by jeffw16 

Also a few more scripts were mentioned as part of the set in the issue #41 
maintenance/ForceSearchIndex.php --skipLinks --indexOnSkip
maintenance/ForceSearchIndex.php --skipParse

2026-02-13 14:36 UTC, cicalese commented
Superseded by #245, which implements this as `canasta maintenance search-index` with wiki farm support and CirrusSearch extension detection.

2026-02-13 14:36 UTC, closed without merging