Daft PR for CLI farm management support
CanastaWiki/Canasta-Go pull request #88
Opened 2023-06-16 17:42 UTC by chl178

2023-06-21 23:31 UTC, chl178 commented
### For people who want to test it locally
As this is an early version for wiki farm support for Canasta, it currently does not support CLI installation and can only be manually installed using docker-compose. You may refer to the official docker-compose manual installation [documentation](https://github.com/CanastaWiki/Canasta-Documentation/blob/main/setup.md#manual-installation) for guidance.
The [test template](https://github.com/CanastaWiki/Canasta-DockerCompose/pull/45) for docker-compose.

1. Modify your `hosts` file to add an alias for 127.0.0.1 and restart the Apache service.
![Screenshot from 2023-06-04 19-54-27](https://github.com/CanastaWiki/Canasta/assets/116774313/f090a958-2c2a-4e93-92c7-8cd8994b5d18)
2. Download my canasta code by `git clone git@github.com:chl178/Canasta.git -b farm` 
3. Create an image by `docker build -t canastafarm . `
4. Download the CLI and use sudo go run canasta.go [commands] to use it

2023-06-21 23:56 UTC, chl178 commented
## Discussion: Program Structure
I would like to initiate a discussion regarding two key elements of our current implementation. This involves the naming convention of our farm management commands and the structure of our docker-compose. Your feedback is crucial in guiding the development of these features.

### 1. Farm Management Command Structure
Currently, we have farm management commands add and remove which share a resemblance to our existing create and delete commands. To distinguish between these functionalities, we're considering the following options:

Place add and remove under a parent farm command: This would result in farm add and farm remove commands. The benefit of this approach is it groups farm-related operations under a single command, improving command organization.

Maintain add and remove at the same level as other commands: This approach keeps the add and remove commands at the same level as other commands, which is how we're currently operating.

Please share your thoughts on these two options or suggest alternate approaches.

### 2. Docker-Compose Structure
Our current docker-compose structure is as follows:

arduino
Copy code
config/
  CommonSettings.php
  Setting1.php
  Setting2.php
  wiki1/
    LocalSettings.php
    settings/
  wiki2/
    LocalSettings.php
    settings/
Each wiki's settings file is contained within a directory of their name under the config directory. These settings include a CommonSettings.php file.

We're trying to decide the naming convention for this common settings file. Should we keep it as CommonSettings.php or change it to LocalSettings.php? Please weigh in with your opinions and any alternate suggestions.

Looking forward to your valuable input on these matters.

2023-06-22 18:51 UTC, olsonjaredm commented
I like using add/remove for the commands (I can't come up with any better terms). 

As far as PHP file structure I'd say default to CommonSettings.php for the upper level with the expectation that for single-wiki 'farms' this file is a stub and ignored by admins.
Then each of the subfolders for individual wikis contain their own LocalSettings.php. I also like the idea of it concatenating all PHP files in the folders so admins can rename them what they like.

2023-07-21 05:13 UTC, jeffw16 requested changes

2023-07-21 05:13 UTC, jeffw16 commented on cmd/add/add.go
> +	fmt.Println("Successfully Added the Wiki '" + name + "in Canasta instance '" + instance.Id + "'...")
shouldn't there be a space between `name +"` and `in Canasta`?

2023-07-21 05:13 UTC, jeffw16 commented on cmd/add/add.go
> +func AddWiki(name, domain, wikipath, siteName, databasePath string, instance config.Installation) error {
Is it possible for any of these params to be non-null but empty? If so, how is that handled?

2023-07-21 05:13 UTC, jeffw16 commented on cmd/remove/remove.go
> +func RemoveWiki(name string, instance config.Installation) error {
What happens if this is removing the last wiki in the Canasta instance?

2023-07-21 05:13 UTC, jeffw16 commented on internal/canasta/canasta.go
> +	err := git.Cloneb(repo, *path, "CLI")
What is `git.Cloneb`? Is it a typo or is it different than `git.Clone`?

2023-07-21 05:13 UTC, jeffw16 commented on internal/canasta/canasta.go
> +	if err := SaveEnvVariable(path+"/.env", "MW_SITE_SERVER", "http://"+domainNames[0]); err != nil {
Let's make sure this isn't `http://`. There should be an option to have `https://` at the very least

2023-07-21 05:13 UTC, jeffw16 commented on internal/canasta/canasta.go
> +	for _, name := range WikiNames {
Is `name` always guaranteed to be nonempty?

2023-11-03 16:47 UTC, merged