Add support for copying override file on create/import
CanastaWiki/Canasta-Go pull request #91
Opened 2023-07-23 14:54 UTC by cicalese

This should fix #90.

2023-07-23 14:54 UTC, cicalese commented
I'm not sure how to test this locally.

2023-07-23 15:22 UTC, hexmode commented
Build error:
``` console
$ go build
go: downloading github.com/spf13/cobra v1.4.0
go: downloading github.com/kirsle/configdir v0.0.0-20170128060238-e45d2f54772f
go: downloading github.com/sethvargo/go-password v0.2.0
go: downloading golang.org/x/term v0.0.0-20220526004731-065cf7ba2467
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
# github.com/CanastaWiki/Canasta-CLI-Go/cmd/import
cmd/import/importExisting.go:69:2: undefined: createCmd

2023-07-23 21:23 UTC, jeffw16 commented
My impression of this PR is: it seems to allow the user to copy over an override file that they can name anything (including names other than `docker-compose.override.yml`). Technically the rest of the CLI is not able to handle that yet.

Also, the concept of an override file seems to be pretty specific to Docker Compose, so this flag should probably fail when invoked for Kubernetes (i.e. when `-o kubernetes` is passed in rather than `-o docker-compose`).

2023-07-24 17:03 UTC, cicalese commented
Yes, I was unsure what to do about other orchestrators. As far as I can tell, the CLI doesn't have a way to add additional arguments on a per-orchestrator basis. That's why I made it so that you can actually copy any single file with this argument, not just docker-compose.override.yml. I'm not 100% happy with it, either, but it is not tied only to docker-compose that way.

2023-07-25 02:03 UTC, cicalese commented
I have tested this locally and confirmed that it works as designed and addresses the issue we needed it for.

2023-07-25 02:58 UTC, jeffw16 commented
What are y'all naming the override file? Are you just passing in `docker-compose.override.yml`?

2023-07-25 03:15 UTC, cicalese commented
Yes, I am indeed just passing in `docker-compose.override.yml`.

2023-07-25 05:05 UTC, jeffw16 requested changes

2023-07-25 05:05 UTC, jeffw16 commented on cmd/create/create.go
> +			if err = createCanasta(canastaInfo, pwd, path, orchestrator, overrideFilename); err != nil {
The Canasta CLI's support for Docker Compose is currently not designed to use an override file that is named anything other than `docker-compose.override.yml`. Would it be possible to change this to a binary flag and eliminate the ability to pick the filename?

2023-07-25 13:52 UTC, cicalese commented on cmd/create/create.go
> +			if err = createCanasta(canastaInfo, pwd, path, orchestrator, overrideFilename); err != nil {
> Would it be possible to change this to a binary flag and eliminate the ability to pick the filename?

Yes, but that would hardcode this feature to work only with docker-compose. Another option would be to create a way to pass parameters to the orchestrator on creation, but that would be a much larger architectural change. Another option would be to change it to copy one or more arbitrary files, to be used however the orchestrator or end user sees fit. That would essentially be the same functionality with slightly broader semantics.

2023-07-25 23:52 UTC, jeffw16 approved these changes
LGTM

2023-07-26 01:08 UTC, cicalese commented
It turned out to be more straightforward than I had anticipated to be able to have the parameter only work when the orchestrator is docker-compose.

This is tested and working.

I do still have a slight preference to providing the filename rather than using a boolean, so that you could specify different override files for different situations (e.g. different port values, different images, replacing some services) . Regardless of the input file name, the file would be copied to docker-compose.override.yml if docker-compose is the orchestrator. If you agree, I can make that change. Otherwise, this should be good to go.

2023-07-26 01:49 UTC, jeffw16 commented
Great, thank you @cicalese!

While I also would prefer to give users the option, the other CLI commands currently don't support using override files that aren't supported by default. For instance, when one does `canasta start`, it calls `docker compose up -d` but it doesn't pass in any other manifest files. If the support is added to all commands, then I think this would be a great feature to add to the Canasta CLI.

2023-07-26 02:10 UTC, cicalese commented
Actually, the import command allows you to specify a .env file and LocalSettings.php file, which is what I initially modeled this after.

2023-07-26 02:36 UTC, cicalese commented
I'm going to add the filename bit in so you can see that it is a minimal change and still is tied only to the docker-compose orchestrator. That way I can also test the patch locally. If you prefer the boolean to the filename after you see it, we can back the commit back out.

2023-07-26 02:58 UTC, cicalese commented
OK, this is tested and confirmed to be working as desired.

To reiterate, the reason this is necessary for the create and import commands is that they are run to create the directory that would hold the canasta instance, including the override file, and then they start the containers. The override file is needed before the containers are started, but it cannot be placed in the canasta directory before the commands are run since the directory does not exist yet at that point.

2023-07-27 01:56 UTC, jeffw16 approved these changes
Ok, this LGTM

2023-07-27 02:31 UTC, yaronkoren approved these changes

2023-07-27 02:33 UTC, merged